databases:
  - name: catidea-postgres
    databaseName: catidea_production
    user: catidea

services:
  - type: redis
    name: catidea-redis
    ipAllowList: []

  - type: web
    name: catidea-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: catidea-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: catidea-redis
          property: connectionString
      - key: ACTION_CABLE_URL
        fromService:
          type: redis
          name: catidea-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: RAILS_LOG_LEVEL
        value: info
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: FRONTEND_URL
        sync: false
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT
    healthCheckPath: /api/v1/health