databases:
  - name: catidea-postgres
    databaseName: catidea_production
    user: catidea

services:
  # Redis アドオン
  - type: redis
    name: catidea-redis
    ipAllowList: []

  # Web/API サービス
  - type: web
    name: catidea-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    preDeployCommand: bundle exec rails db:migrate
    healthCheckPath: /api/v1/health

    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: catidea-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: catidea-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RAILS_LOG_LEVEL
        value: info
      - key: RAILS_SERVE_STATIC_FILES
        value: true
